mixertrackitem.cpp setMidiChannelAndPort WIP

diff --git a/build/package_mac b/build/package_mac
--- a/build/package_mac
+++ b/build/package_mac
@@ -1,19 +1,31 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 APPNAME=mscore
-LONG_NAME=MuseScore
+LONG_NAME="MuseScore"
+LONGER_NAME="MuseScore 3"
+VERSION=0
+DEVELOPER_NAME="MuseScore"
 
-if [[ $1 ]]
-then
-    LONG_NAME=MuseScoreNightly
-    LONGER_NAME=MuseScoreNightly
-    VERSION=$1
-else
-    LONG_NAME=MuseScore
-    LONGER_NAME="MuseScore 3"
-    VERSION=3.2.0
-fi
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        --long_name) LONG_NAME="$2"; shift ;;
+        --longer_name) LONGER_NAME="$2"; shift ;;
+        --version) VERSION="$2"; shift ;;
+        --developer_name) DEVELOPER_NAME="$2"; shift ;;
+        *) echo "Unknown parameter passed: $1"; exit 1 ;;
+    esac
+    shift
+done
 
+if [ "$VERSION" == "0" ]; then 
+    SCRIPT_DIR=$(cd "$(dirname ${BASH_SOURCE[0]})" && pwd)
+    VERSION=$(cmake -P "$SCRIPT_DIR/../config.cmake" | sed -n -e "s/^.*VERSION  *//p")
+fi    
+
+echo "LONG_NAME: $LONG_NAME"
+echo "LONGER_NAME: $LONGER_NAME"
+echo "VERSION: $VERSION"
+echo "DEVELOPER_NAME: $DEVELOPER_NAME"
 
 WORKING_DIRECTORY=applebuild
 BACKGROUND=build/packaging/musescore-dmg-background.tiff
@@ -35,7 +47,7 @@ function set_bundle_display_options() {
                 set statusbar visible to false
                 set current view to icon view
                 delay 1 -- sync
-                set the bounds to {0, 0, 540, 300}
+                set the bounds to {0, 0, 540, 345}
             end tell
             delay 1 -- sync
             set icon size of the icon view options of container window to 128
@@ -45,7 +57,7 @@ function set_bundle_display_options() {
             set position of item "Applications" to {150,110}
             open
             set background picture of the icon view options of container window to file "background.tiff" of folder "Pictures"
-            set the bounds of the container window to {0, 0, 540, 300}
+            set the bounds of the container window to {0, 0, 540, 345}
             update without registering applications
             delay 5 -- sync
             close
@@ -83,23 +95,10 @@ function change_rpath() {
    done
 }
 
-function change_rpath_QWebEngine() {
-   for P in `otool -L $1 | awk '{print $1}'`
-   do
-      if [[ "$P" == *@rpath* ]]
-      then
-         PSLASH=$(echo $P | sed 's,@rpath,@loader_path/../../../../../../..,g')
-         FNAME=$(echo $P | sed "s,@rpath,${VOLUME}/${APPNAME}.app/Contents/Frameworks,g")
-         install_name_tool -change $P $PSLASH $1
-      fi
-   done
-}
-
-
-rm ${WORKING_DIRECTORY}/${COMPRESSEDDMGNAME}
+rm -f ${WORKING_DIRECTORY}/${COMPRESSEDDMGNAME}
 
 #tip: increase the size if error on copy or macdeployqt
-hdiutil create -size 500m -fs HFS+ -volname ${VOLNAME} ${WORKING_DIRECTORY}/${DMGNAME}
+hdiutil create -size 800m -fs HFS+ -volname ${VOLNAME} ${WORKING_DIRECTORY}/${DMGNAME}
 
 # Mount the disk image
 hdiutil attach ${WORKING_DIRECTORY}/${DMGNAME}
@@ -142,9 +141,6 @@ macdeployqt ${VOLUME}/${APPNAME}.app
 # fix the libs, qt5.6 has @rpath...
 BIN_FILE=${VOLUME}/${APPNAME}.app/Contents/MacOS/mscore
 change_rpath $BIN_FILE
-# fix the QWebEngineProcess, qt5.9 has @rpath...
-WebEngineProcess=${VOLUME}/${APPNAME}.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
-change_rpath_QWebEngine $WebEngineProcess
 
 # Workaround:
 # fix Homebrew libraries with hard coded absolute path, see QTBUG-56814
@@ -173,7 +169,6 @@ do
 done
 
 otool -L ${VOLUME}/${APPNAME}.app/Contents/MacOS/mscore
-otool -L ${VOLUME}/${APPNAME}.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
 
 echo "Rename ${APPNAME}.app to ${VOLUME}/${LONGER_NAME}.app"
 mv ${VOLUME}/${APPNAME}.app "${VOLUME}/${LONGER_NAME}.app"
@@ -186,22 +181,42 @@ mkdir -p ${VOLUME}/Pictures
 cp  ${BACKGROUND} ${VOLUME}/Pictures/background.tiff
 
 echo "symlink application"
-# nssymlink applicatio
+# nssymlink application
 ln -s /Applications/ ${VOLUME}/Applications
 set_bundle_display_options ${VOLUME}
 mv ${VOLUME}/Pictures ${VOLUME}/.Pictures
 
+# Most nested locations should go first
+CODE_PATHS=(
+    "${VOLUME}/${LONGER_NAME}.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app"
+    "${VOLUME}/${LONGER_NAME}.app"
+)
+
 #codesign
 echo "Codesign"
-codesign --deep -s "Developer ID Application: MuseScore" "${VOLUME}/${LONGER_NAME}.app"
+# `codesign --deep` doesn't seem to search for code in Contents/Resources directory so sign libraries in it manually
+find "${VOLUME}/${LONGER_NAME}.app/Contents/Resources" -name '*.dylib' -exec codesign --force --options runtime --deep -s "Developer ID Application: ${DEVELOPER_NAME}" '{}' ';'
+# Sign code in other (more conventional) locations
+codesign --force --options runtime --entitlements "${WORKING_DIRECTORY}/../build/macosx_entitlements.plist" --deep -s "Developer ID Application: ${DEVELOPER_NAME}" "${CODE_PATHS[@]}"
 echo "spctl"
 spctl --assess --type execute "${VOLUME}/${LONGER_NAME}.app"
 echo "Codesign verify"
-codesign --verify --deep --strict --verbose=2 "${VOLUME}/${LONGER_NAME}.app"
+codesign --verify --deep --strict --verbose=2 "${CODE_PATHS[@]}"
 
 echo "Unmount"
-# Unmount the disk image
-hdiutil detach $DEV
+for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
+    # Unmount the disk image
+    hdiutil detach $DEV
+    if [ $? -eq 0 ]; then
+        break
+    fi
+    if [ $i -eq 20 ]; then
+        echo "Failed to unmount the disk image; exiting after 20 retries."
+        exit 1
+    fi
+    echo "Failed to unmount the disk image; retrying in 30s"
+    sleep 30
+done
 
 # Convert the disk image to read-only
 hdiutil convert ${WORKING_DIRECTORY}/${DMGNAME} -format UDBZ -o ${WORKING_DIRECTORY}/${COMPRESSEDDMGNAME}
